# ===================== FUNCIONAL - DESARROLLO =====================

# ---------- ETAPA DE BUILD ----------
FROM    docker.io/library/golang:1.24.5-alpine3.22  AS  builder

WORKDIR /app

# COPY  .   .
#COPY    go.sum  .
#COPY    go.mod  .
COPY    go.mod  go.sum ./
RUN     go  mod download

COPY    . .
RUN     go build -o main ./cmd/server

# ---------- ETAPA FINAL ----------
FROM    docker.io/library/golang:1.24.5-alpine3.22

WORKDIR /app

COPY    --from=builder  /app/main   ./

CMD ["./main"]